#!/usr/bin/env python3
"""The one loader for the UK export / re-export overlay recipe (workstream B1 of
COMPLETION_PLAN.md).

Until the export flows are materialised into country_year_final (B2), every consumer
of flow='export_uk' / 'reexport' rows rebuilds the same state at load time:

    country_obs rows (+ inf-only closing sections from inf_fallback)
      -> value overlays, keyed on the RAW parse and the BAD value (eight CSVs, in order)
      -> fused-section splits (row_seq range, sets group/article/unit)
      -> phantom-region relabel
      -> heading promotion (optional; the explorer uses it)
      -> group reassign (group_reassign.csv, then capture_reassign.csv)
      -> group-name folds -> export_group_families

Before this module the value-overlay loader lived in four scripts and the reassign /
fold / family loaders in two; each copy had to be edited in step.  Everything here is
a straight lift of those copies -- the regression test is that the four consumers'
outputs are byte-identical before and after (see reports/canada_completion_log.md,
workstream B1).

Conventions shared by every consumer and encoded here:

* A repair is keyed on (volume, year, RAW group, RAW article, country_raw,
  round(old_value)).  Keyed on the bad value as well as the coordinates so a
  correction can only ever replace the exact number it was derived from: if the parse
  changes upstream the key stops matching and the repair drops out rather than
  silently overwriting a different figure.  A BLANK new_value is a null-out -- the cell
  is malformed with no witness anywhere and must be dropped, not trusted.
* Repairs are looked up on the raw labels BEFORE any relabelling pass.
* A volume is the primary witness for its maximum year only (as_1897 carries 1893-97
  but is primary for 1897; tn_1871 is primary for 1870), except PRIMARY_OVERRIDE.
"""
import csv
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import inf_fallback
from phantom_articles import (fix_articles, known_groups, promote_headings,
                              load_splits, apply_splits)

# The eight value-overlay files, applied in this order (a later file wins a
# coordinate collision). export_manual_repairs.csv is HAND-EDITED; the rest are
# regenerated by the scripts named in PIPELINE.md section 2.
REPAIR_FILES = ('reference/export_cell_repairs.csv',
                'reference/malformed_cell_repairs.csv',
                'reference/edge_column_repairs.csv',
                'reference/row_slip_repairs.csv',
                'reference/scaled_block_repairs.csv',
                'reference/label_merge_repairs.csv',
                'reference/export_manual_repairs.csv',
                'reference/section_closure_repairs.csv')
REASSIGN_FILES = ('reference/group_reassign.csv',
                  'reference/capture_reassign.csv')
FOLDS_FILE = 'reference/group_name_folds.csv'
FAMILIES_FILE = 'reference/export_group_families.csv'

NO_REPAIR = object()

# Per-year primary-witness OVERRIDE. A volume's own maximum year sits in the
# damaged page-edge column of the ten-column comparative layout, so for 1897
# and 1898 the volume-of-record is the WORST witness: measured closure says
# as_1899's mid-table reprint columns corroborate roughly 3x more value than
# the vote-repaired edge columns (Canada 1897: 22.0% of value against 2.1%).
# Those years are therefore read from as_1899. 1899 stays on as_1899's own
# edge column -- the one reprint, tn_1901's mid-table 1899 column
# (parse_tn_overlap.py -> country_obs_tn), closes no better and is a
# different publication whose headings align poorly, so it serves as a
# WITNESS to repair as_1899 (repair_edge_columns.py, repair_section_closure.py)
# rather than as the primary.
PRIMARY_OVERRIDE = {1897: 'as_1899', 1898: 'as_1899'}

TOTAL_RE = re.compile(r'\bTOTAL\b', re.I)

# Canada's destination labels in the UK Statements: one aggregate (including
# Newfoundland) to 1896, split from 1897.
CANADA_LABELS = ('British North America', 'Canada', 'Newfoundland')


def is_total(s):
    return bool(s) and bool(TOTAL_RE.search(s))


def is_primary(vol, year, own_year):
    """own_year: {volume: max year it carries}."""
    if year in PRIMARY_OVERRIDE:
        return vol == PRIMARY_OVERRIDE[year]
    return own_year.get(vol) == year


# ----------------------------------------------------------------------------
# value overlays
# ----------------------------------------------------------------------------

def load_repairs(paths=REPAIR_FILES):
    """{(volume, year, raw_group, raw_article, country_raw, round(old)): new}
    where new is a float or None (null-out)."""
    out = {}
    for path in paths:
        if not os.path.exists(path):
            continue
        for r in csv.DictReader(open(path)):
            out[(r['volume'], int(r['year']), r['article_group'], r['article'],
                 r['country_raw'], round(float(r['old_value'])))] = (
                float(r['new_value']) if r['new_value'] != '' else None)
    return out


def repair_value(fix, vol, year, raw_group, raw_article, country_raw, value):
    """Return (value, applied).  value None = null-out (drop the cell)."""
    if value is None or not fix:
        return value, False
    nv = fix.get((vol, year, raw_group, raw_article or '', country_raw,
                  round(value)), NO_REPAIR)
    if nv is NO_REPAIR:
        return value, False
    return nv, True


# ----------------------------------------------------------------------------
# label overlays
# ----------------------------------------------------------------------------

def load_folds(flow, path=FOLDS_FILE):
    if not os.path.exists(path):
        return {}
    return {r['raw_group']: r['canonical']
            for r in csv.DictReader(open(path)) if r['flow'] == flow}


def load_reassign(flow, paths=REASSIGN_FILES):
    """{(volume, from_group, article): to_group}; capture_reassign.csv is read
    after group_reassign.csv and wins a collision."""
    out = {}
    for path in paths:
        if not os.path.exists(path):
            continue
        for r in csv.DictReader(open(path)):
            if r['flow'] == flow:
                out[(r['volume'], r['from_group'], r['article'])] = r['to_group']
    return out


def load_families(flow, path=FAMILIES_FILE):
    """Era wordings, OCR variants and continuation suffixes of one printed
    heading -> one family label, applied after the group-name folds.  IRON (to
    1890) and IRON AND STEEL (from 1891) are one series; CAOUTCHOUC has seven
    spellings; "IRON AND STEEL'd)" is a page continuation."""
    if not os.path.exists(path):
        return {}
    return {r['canonical']: r['family']
            for r in csv.DictReader(open(path)) if r['flow'] == flow}


# ----------------------------------------------------------------------------
# rows
# ----------------------------------------------------------------------------

def load_flow_rows(con, flow, with_qty=False, table='country_obs'):
    """Raw rows of one flow as tuples
        (volume, flow, year, group, article, unit, row_seq, country_raw, value[, quantity])
    with the inf-only closing sections appended when reading country_obs."""
    cols = {c[0] for c in con.execute(f'describe "{table}"').fetchall()}
    seq = 'row_seq' if 'row_seq' in cols else 'rowid'
    qty = ', ' + ('quantity' if 'quantity' in cols else 'NULL') if with_qty else ''
    rows = con.execute(f"""
        select volume, flow, year, coalesce(article_group,'') ag, article,
               unit, {seq} seq, country_raw, value{qty}
        from "{table}" where flow = ?
    """, [flow]).fetchall()
    if table == 'country_obs':
        rows += inf_fallback.load_rows(flow, with_qty=with_qty)
    return rows


def relabel(rows, flow, con=None, promote=False):
    """The label passes, in order: fused-section splits -> phantom-region
    relabel -> (optionally) heading promotion.  Returns a parallel list; the
    caller zips it with the raw rows because repairs are keyed on the raw
    labels.  Row layout is the load_flow_rows() one."""
    out = apply_splits(rows, load_splits(flow=flow), vol=0, flow=1, year=2,
                       group=3, art=4, seq=6, unit=5)
    out = fix_articles(out, vol=0, flow=1, year=2, group=3, art=4, unit=5, seq=6)
    if promote:
        if con is None:
            raise ValueError('promote_headings needs the DuckDB connection')
        out = promote_headings(out, known_groups(con, flow), vol=0, flow=1,
                               year=2, group=3, art=4)
    return out
