#!/usr/bin/env python3
"""A confidence card for a family of commodities.

"Is this commodity 95% right?" cannot be answered by the closure test alone —
closure is preserved by relabelling, blind to a section lost in only some
years, and only as good as the anchor it measures against. So this card
reports what each commodity-year actually PASSES, test by test:

    q   the country rows sum to the printed national quantity
    v   the country rows sum to the printed national value
    qv  BOTH columns close — two independent tests of the same block, and
        the strongest statement the data can make about a year without
        going to the page image

and then lists, per family, what the source-level instruments still hold
against it: contested anchors (anchor_disagreement.py), relabelled blocks
(cross_engine_labels.py) and unrepaired digit candidates
(digit_repair_candidates.py).

    python3 scripts/family_confidence.py --family oil,tallow,lard \\
        --title "Fats and oils" > reports/oils_confidence.md
"""
import collections
import csv
import json
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
TOL = 0.001


def close(got, want, tol=TOL):
    return bool(got) and bool(want) and abs(got - want) / want <= tol


def main():
    fam = ['oil']
    if '--family' in sys.argv:
        fam = [s.strip().lower()
               for s in sys.argv[sys.argv.index('--family') + 1].split(',')]
    title = 'Family'
    if '--title' in sys.argv:
        title = sys.argv[sys.argv.index('--title') + 1]

    # Measured on map_slim.json, NOT the raw payload: the shipped file is the
    # one whose parent-and-children double counts have been resolved. Judging
    # tallow on the payload reads 1.4-1.8 through the 1890s purely because
    # 'Australasia' and 'Victoria' are both still present there.
    slim = json.load(open(BASE / 'exports' / 'map_slim.json'))['commodities']
    cards = []
    for name, entry in sorted(slim.items(), key=lambda kv: -(kv[1]['v'] or 0)):
        if not any(f in name.lower() for f in fam):
            continue
        t1q = {int(y): q for y, q in (entry.get('t1') or {}).items() if q}
        t1v = {int(y): v for y, v in (entry.get('t1v') or {}).items() if v}
        if not t1q and not t1v:
            continue
        qsum, vsum = collections.Counter(), collections.Counter()
        for c, byy in entry['c'].items():
            for y, cell in byy.items():
                vsum[int(y)] += cell[0]
                qsum[int(y)] += cell[1]
        for y, cell in (entry.get('res') or {}).items():
            vsum[int(y)] += cell[0]
            qsum[int(y)] += cell[1]

        qunit = entry.get('u', '')
        # A year with a printed national total and NO origin table is not a
        # failure, it is a year the Abstract never broke down by country
        # (about a quarter of the corpus by value). Counting those in the
        # denominator would read as a defect and hide the real one, so they
        # get their own column.
        allyears = sorted(set(t1q) | set(t1v))
        years = [y for y in allyears if qsum.get(y) or vsum.get(y)]
        noorig = len(allyears) - len(years)
        nq = sum(close(qsum[y], t1q.get(y)) for y in years)
        nv = sum(close(vsum[y], t1v.get(y)) for y in years)
        nboth = sum(close(qsum[y], t1q.get(y)) and close(vsum[y], t1v.get(y))
                    for y in years)
        nboth5 = sum(close(qsum[y], t1q.get(y), .05) and
                     close(vsum[y], t1v.get(y), .05) for y in years)
        nq5 = sum(close(qsum[y], t1q.get(y), .05) for y in years)
        cards.append({
            'commodity': name, 'gbp': round(entry['v'] or 0),
            'flags': ' '.join(entry.get('q') or ()),
            'years': len(years), 'no_origins': noorig,
            'q_measurable': sum(1 for y in years if t1q.get(y)),
            'v_measurable': sum(1 for y in years if t1v.get(y)),
            'q_close': nq, 'v_close': nv, 'both_close': nboth,
            'q_close5': nq5, 'both_close5': nboth5,
            'unit': qunit or '',
        })

    tot = collections.Counter()
    for k in cards:
        for f in ('years', 'no_origins', 'q_measurable', 'v_measurable',
                  'q_close', 'v_close', 'both_close', 'q_close5',
                  'both_close5'):
            tot[f] += k[f]
        tot['gbp'] += k['gbp']

    print(f'# {title}: what each commodity-year passes\n')
    print(f'Generated by `scripts/family_confidence.py --family '
          f'{",".join(fam)}`.\n')
    print('`q` = the origin rows sum to the printed national quantity within '
          '0.1%; `v` = the same for the printed national value; `qv` = both. '
          'Two columns closing on the same block are two independent tests, '
          'which is the strongest statement available short of the page '
          'image.\n')
    print('| GBP | commodity | unit | years with origins | q closes '
          '| v closes | **qv** | no origin table | map flags |')
    print('|---|---|---|---|---|---|---|---|---|')
    for k in cards:
        print(f'| {k["gbp"]:,} | `{k["commodity"]}` | {k["unit"]} | '
              f'{k["years"]} | {k["q_close"]}/{k["q_measurable"]} | '
              f'{k["v_close"]}/{k["v_measurable"]} | '
              f'**{k["both_close"]}/{k["years"]}** | {k["no_origins"]} '
              f'| {k["flags"]} |')
    print(f'\n**Family total**: {tot["gbp"]:,} GBP, {tot["years"]} '
          f'commodity-years. Quantity closes in {tot["q_close"]} of '
          f'{tot["q_measurable"]} measurable years '
          f'({100 * tot["q_close"] / max(tot["q_measurable"], 1):.0f}%), value '
          f'in {tot["v_close"]} of {tot["v_measurable"]} '
          f'({100 * tot["v_close"] / max(tot["v_measurable"], 1):.0f}%), '
          f'**both in {tot["both_close"]} of {tot["years"]} '
          f'({100 * tot["both_close"] / max(tot["years"], 1):.0f}%)**.\n')
    print(f'At the looser 5% tolerance earlier sessions quoted: quantity '
          f'{tot["q_close5"]} of {tot["q_measurable"]} '
          f'({100 * tot["q_close5"] / max(tot["q_measurable"], 1):.0f}%), '
          f'both columns {tot["both_close5"]} of {tot["years"]} '
          f'({100 * tot["both_close5"] / max(tot["years"], 1):.0f}%).\n')

    def hits(path, textcols, extra=()):
        out = []
        if not (BASE / 'reports' / path).exists():
            return out
        for r in csv.DictReader(open(BASE / 'reports' / path)):
            txt = ' '.join((r.get(c) or '') for c in textcols).lower()
            if any(f in txt for f in fam):
                out.append(r)
        return out

    slips = hits('cross_engine_label_slips.csv', ('group', 'article'))
    print(f'## Blocks whose two readings disagree about the LABELS '
          f'({len(slips)})\n')
    print('Closure cannot see these: relabelling preserves the sum.\n')
    print('| GBP | volume | year | block | slip | settled by |')
    print('|---|---|---|---|---|---|')
    for r in sorted(slips, key=lambda r: -int(r['gbp']))[:25]:
        verdict = (r['row_set_closes'] + ' (segment arithmetic)'
                   if r['row_set_closes'] else r['third_voice'])
        print(f'| {int(r["gbp"]):,} | {r["volume"]} | {r["year"]} | '
              f'{r["group"]} \\| {r["article"]} | {r["slip"]} | {verdict} |')

    digs = hits('digit_repair_candidates.csv', ('group', 'article'))
    strong, seen_d = [], set()
    for r in digs:
        # the same printed line is read by both engines, so a repair the
        # arithmetic finds in one block is usually offered twice
        k = (r['year'], r['country'], r['column'], r['reads'], r['should_be'])
        if r['strong'] == 'True' and k not in seen_d:
            seen_d.add(k)
            strong.append(r)
    print(f'\n## One-digit repairs still outstanding ({len(strong)} '
          f'corroborated, of {len(digs)} arithmetically possible)\n')
    print('| volume | year | block | country | col | reads | should be | '
          'other engine |')
    print('|---|---|---|---|---|---|---|---|')
    for r in strong[:30]:
        print(f'| {r["volume"]} | {r["year"]} | {r["group"]} \\| '
              f'{r["article"]} | {r["country"]} | {r["column"]} | '
              f'{int(r["reads"]):,} | {int(r["should_be"]):,} | '
              f'{"yes" if r["other_engine_agrees"] == "True" else "no"} |')

    anch = hits('anchor_disagreements.csv', ('group', 'article', 'commodity'))
    bad = [r for r in anch if r['verdict'] == 'ORIGINS-FAVOUR-LOSER']
    # a 0.002% spread between two printings is a comma, not a dispute; only
    # a disagreement big enough to move the closure test is worth a line here
    mat = [r for r in anch if float(r['spread_pct']) >= 0.5 or r['verdict']]
    print(f'\n## Anchors the volumes disagree about ({len(anch)}, of which '
          f'{len(mat)} by more than 0.5% or with an origin-sum verdict; '
          f'{len(bad)} where the origin sum backs a losing reading)\n')
    for r in sorted(mat, key=lambda r: -int(r['gbp'] or 0))[:15]:
        print(f'- {r["year"]} `{r["group"]} | {r["article"]}` '
              f'({r["measure"]}): vote {int(r["winner"]):,}, spread '
              f'{r["spread_pct"]}% — {r["candidates"][:110]}'
              f'{"  **" + r["verdict"] + "**" if r["verdict"] else ""}')


if __name__ == '__main__':
    main()
