#!/usr/bin/env python3
"""The mirror: UK exports to Canada vs Canadian imports from Great Britain
(workstream C1 of COMPLETION_PLAN.md; the rules are its section 1).

    python3 scripts/mirror_canada_uk.py [--rate 4.8666] [--out reports/mirror_canada_uk.md]

Two governments recorded the same goods crossing the same ocean.  The UK Annual
Statement gives declared value f.o.b. British port of British produce and of foreign
re-exports, by destination, per CALENDAR year.  The Canadian Trade & Navigation
returns give value imported ("fair market value in the country whence exported"), by
country, per FISCAL year: 1 July - 30 June for FY1868-1906, nine months to 31 March
1907, then 1 April - 31 March.  No twelve months coincide, so this is a RATIO-BAND
INSTRUMENT, never a closure proof.

Rules (COMPLETION_PLAN.md section 1):
  T1  blend, never shift:  UK CY(y)  vs  0.5*FY(y) + 0.5*FY(y+1)   (FY1868-1906)
      from CY1908: 0.25*FY(y) + 0.75*FY(y+1); FY1907 scaled by 12/9 and marked.
  T2  the three-year sum is the stricter test (cancels lag and seasonality).
  T3  single-year blended ratio within +-15% = pass; three-year within +-8% = pass;
      outside both = FLAG on whichever side is not at print.
  T4  Canadian tables keep fiscal years; the blend exists only here.
Money: Canadian customs converted at GBP1 = $4.8666.  Geography: 'British North
America' on the UK side INCLUDES Newfoundland through 1896 (an upward bias on the UK
side, stated not corrected); 'Canada' and 'Newfoundland' are printed separately from
1897 and only 'Canada' is used.  The UK side must include re-exports.

Inputs (all regenerated by PIPELINE.md sections 2 and 3):
  reports/canada_export_series.csv      British produce, own-year rows (export_country_series.py)
  reports/canada_reexport_series.csv    foreign re-exports, same script with --flow reexport
  exports/canada_imports_country_year.csv   parsed Canadian imports by country x FY
  reference/canada_country_series_voted.csv printed EfC by country (the Canadian side at print, 1873-89)
Output: reports/mirror_canada_uk.md and reports/mirror_canada_uk.csv
"""
import argparse
import collections
import csv
import os

RATE = 4.8666
SINGLE_TOL = 0.15
TRIPLE_TOL = 0.08
FY_MONTHS = {1907: 9}


def fnum(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return 0.0


def uk_side(path, exclude=('newfoundland',)):
    """{year: GBP} over own-year rows, summed across the labels except Newfoundland
    (from 1897 the Statement prints it separately and the Canadian side never
    includes it).  Also returns the Newfoundland-only sum for the caveat."""
    tot, nfld, cells = collections.Counter(), collections.Counter(), collections.Counter()
    if not os.path.exists(path):
        return tot, nfld, cells
    for r in csv.DictReader(open(path)):
        if r['own_year'] != '1':
            continue
        y = int(r['year'])
        v = fnum(r['value'])
        if r['country'].strip().lower() in exclude:
            nfld[y] += v
            continue
        tot[y] += v
        cells[y] += 1
    return tot, nfld, cells


def canada_side(path, col):
    """{fy: $} of imports from Great Britain."""
    out = collections.Counter()
    for r in csv.DictReader(open(path)):
        if r['country'].strip().lower() == 'great britain':
            out[int(r['fiscal_year'])] += fnum(r[col])
    return out


def canada_printed(path, measure='efc'):
    out = {}
    if not os.path.exists(path):
        return out
    for r in csv.DictReader(open(path)):
        if r['measure'] == measure and r['country'].strip().lower() == 'great britain':
            out[int(r['fiscal_year'])] = fnum(r['value'])
    return out


def annualised(fy_val, fy):
    """Scale a short fiscal year to twelve months (FY1907 = 9 months)."""
    m = FY_MONTHS.get(fy, 12)
    return fy_val * 12.0 / m if m != 12 else fy_val


def blend(ca, y):
    """T1: the Canadian dollars covering UK calendar year y, or None if either
    fiscal year is missing."""
    a, b = ca.get(y), ca.get(y + 1)
    if a is None or b is None or a == 0 or b == 0:
        return None
    a, b = annualised(a, y), annualised(b, y + 1)
    if y >= 1908:
        return 0.25 * a + 0.75 * b
    return 0.5 * a + 0.5 * b


def verdict(single, triple):
    if single is None:
        return 'no data'
    ok1 = abs(single - 1) <= SINGLE_TOL
    ok3 = triple is not None and abs(triple - 1) <= TRIPLE_TOL
    if ok1 and (ok3 or triple is None):
        return 'pass'
    if ok1 or ok3:
        return 'pass (one test)'
    return 'FLAG'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rate', type=float, default=RATE)
    ap.add_argument('--produce', default='reports/canada_export_series.csv')
    ap.add_argument('--reexport', default='reports/canada_reexport_series.csv')
    ap.add_argument('--canada', default='exports/canada_imports_country_year.csv')
    ap.add_argument('--printed', default='reference/canada_country_series_voted.csv')
    ap.add_argument('--out', default='reports/mirror_canada_uk.md')
    a = ap.parse_args()

    prod, prod_nf, prod_cells = uk_side(a.produce)
    reex, reex_nf, reex_cells = uk_side(a.reexport)
    ca_imp = canada_side(a.canada, 'val_imp')
    ca_efc = canada_side(a.canada, 'val_efc')
    ca_print = canada_printed(a.printed)

    years = sorted(set(prod) | set(reex))
    recs = []
    for y in years:
        uk_gbp = prod.get(y, 0) + reex.get(y, 0)
        uk_usd = uk_gbp * a.rate
        bl = blend(ca_imp, y)
        bl_print = blend(ca_print, y)
        recs.append(dict(year=y, uk_produce=prod.get(y, 0), uk_reexport=reex.get(y, 0),
                         uk_gbp=uk_gbp, uk_usd=uk_usd, uk_cells=prod_cells.get(y, 0) + reex_cells.get(y, 0),
                         nfld_gbp=prod_nf.get(y, 0) + reex_nf.get(y, 0),
                         fy_a=ca_imp.get(y), fy_b=ca_imp.get(y + 1), blend=bl,
                         ratio=(bl / uk_usd if bl and uk_usd else None),
                         blend_printed=bl_print,
                         ratio_printed=(bl_print / uk_usd if bl_print and uk_usd else None)))
    # T2: three-year sums centred on y
    by = {r['year']: r for r in recs}
    for r in recs:
        y = r['year']
        win = [by.get(y + d) for d in (-1, 0, 1)]
        if all(w and w['blend'] and w['uk_usd'] for w in win):
            r['ratio3'] = sum(w['blend'] for w in win) / sum(w['uk_usd'] for w in win)
        else:
            r['ratio3'] = None
        r['verdict'] = verdict(r['ratio'], r['ratio3'])

    # ---- csv
    csv_path = a.out.rsplit('.', 1)[0] + '.csv'
    with open(csv_path, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(recs[0].keys()))
        w.writeheader()
        w.writerows(recs)

    # ---- md
    n_pass = sum(r['verdict'].startswith('pass') for r in recs)
    n_flag = sum(r['verdict'] == 'FLAG' for r in recs)
    n_data = sum(r['ratio'] is not None for r in recs)
    L = []
    L.append('# The mirror: UK exports to Canada vs Canadian imports from Great Britain\n')
    L.append('Generated by `scripts/mirror_canada_uk.py`. A ratio-band instrument, never a closure '
             'proof: the UK side is a calendar year, the Canadian side is blended from two fiscal '
             'years (1 July - 30 June) per `COMPLETION_PLAN.md` section 1. '
             f'Sterling converted at GBP1 = ${a.rate}. UK side = British produce + foreign re-exports, '
             'own-year rows of the parsed destination tables (no printed by-destination total exists '
             'in the corpus, so the UK side is a floor). '
             'Canadian side = value imported from Great Britain, parsed General Statement; the '
             '"printed" column uses the prefatory by-country series of value entered for consumption '
             '(the Canadian side at print, 1873-89).\n')
    L.append(f'**Years with both sides: {n_data}. Pass: {n_pass}. Flag: {n_flag}.** '
             f'Pass = blended single-year ratio within +-{SINGLE_TOL:.0%} and three-year ratio within '
             f'+-{TRIPLE_TOL:.0%} (or only one test available); "pass (one test)" = one of the two.\n')
    L.append('Geography caveat: through 1896 the UK label is "British North America", which includes '
             'Newfoundland; the Canadian side never does. The UK side therefore carries an upward '
             'bias before 1897 (stated, not corrected). From 1897 the Newfoundland rows are excluded '
             '(column `Nfld GBP`).\n')
    L.append('| CY | UK produce GBP | UK re-exp GBP | UK total $ | cells | FY(y) $ | FY(y+1) $ | blend $ | '
             'ratio | 3-yr | printed ratio | verdict | Nfld GBP |')
    L.append('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|')

    def m(x):
        return f'{x:,.0f}' if x else '-'

    def rt(x):
        return f'{x:.2f}' if x else '-'

    for r in recs:
        L.append(f"| {r['year']} | {m(r['uk_produce'])} | {m(r['uk_reexport'])} | {m(r['uk_usd'])} | "
                 f"{r['uk_cells']} | {m(r['fy_a'])} | {m(r['fy_b'])} | {m(r['blend'])} | "
                 f"{rt(r['ratio'])} | {rt(r['ratio3'])} | {rt(r['ratio_printed'])} | "
                 f"{r['verdict']} | {m(r['nfld_gbp'])} |")
    L.append('')
    L.append('## Reading the flags\n')
    L.append('A ratio above 1 means Canada recorded more arriving from Britain than Britain recorded '
             'sending. Small excesses are expected (freight and insurance are not in either value, but '
             'Canadian "fair market value" runs a little above f.o.b.; the UK side is a floor). A ratio '
             'far above 1 with the Canadian side at print (printed ratio agrees) points at the UK '
             'export parse for that year; a ratio far below 1 points at the Canadian parse. Confirm '
             'any single-year flag with the three-year column before acting on it.\n')
    flagged = [r for r in recs if r['verdict'] == 'FLAG']
    if flagged:
        L.append('Flagged years: ' + ', '.join(
            f"{r['year']} ({rt(r['ratio'])}, 3-yr {rt(r['ratio3'])})" for r in flagged) + '.\n')
    missing = [r['year'] for r in recs if r['ratio'] is None]
    if missing:
        L.append('No Canadian side yet for CY ' + ', '.join(map(str, missing)) +
                 ' (fiscal years not yet in `exports/canada_imports_country_year.csv`; workstreams A1/A2).\n')
    open(a.out, 'w').write('\n'.join(L))
    print(f'wrote {a.out} and {csv_path}: {n_data} years, {n_pass} pass, {n_flag} flag')
    for r in recs:
        if r['ratio'] is not None:
            print(f"{r['year']}  UK ${r['uk_usd']/1e6:6.1f}M  blend ${r['blend']/1e6:6.1f}M  "
                  f"ratio {r['ratio']:.2f}  3yr {rt(r['ratio3'])}  printed {rt(r['ratio_printed'])}  {r['verdict']}")


if __name__ == '__main__':
    main()
